# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomalloc', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('UNDER', 'UNDERGRAD'), ('GRAD', 'GRADUATE'), ('PROF', 'PROFESSOR')], default='UNDER', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
