# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomalloc', '0003_auto_20171116_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
