# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomalloc', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=200),
        ),
    ]
