# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomalloc', '0007_auto_20171120_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remain',
            field=models.IntegerField(default=3, help_text='Chances for penalty'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='real_amount',
            field=models.IntegerField(default=0, help_text='Real amout of people at room'),
        ),
    ]
