# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-06 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomalloc', '0009_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='subject',
        ),
    ]
